//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainReservationSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedTicket
    {
        public int BookingId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TrainNumber { get; set; }
        public string @class { get; set; }
        public Nullable<int> numberofberths { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> TotalAmt { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
